name: CI - sfos3.3 branch on SFOS 3.3.0 (armv7hl,i486) & SFOS 4.0.1 (aarch64)


env:
  sfos_target: 3.3.0.14

on:
  push:
    tags:
      - 'sfos3.3_release/*'
      - 'sfos3.3_rc/*'
      - 'sfos3.3_beta/*'
      - 'sfos3.3_alpha/*'
      - 'sfos3.3_test/*'
      - 'sfos3.3/*'
  pull_request:
    branches:
      - sfos3.3

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 3
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache SDK images
      id: cache-sdk
      uses: actions/cache@v3
      with:
        path: coderus/github-sfos-build@*
              coderus/*sailfishos-platform-sdk*
        key: cache

    - name: Prepare
      run: mkdir RPMS

    - name: Build aarch64
      uses: coderus/github-sfos-build@old-stable
      with:
        release: 4.0.1.45
        arch: aarch64

    - name: Build armv7hl
      uses: coderus/github-sfos-build@old-stable
      with:
        release: ${{ env.sfos_target }}
        arch: armv7hl

    - name: Build i486
      uses: coderus/github-sfos-build@old-stable
      with:
        release: ${{ env.sfos_target }}
        arch: i486

    - name: Upload build result
      uses: actions/upload-artifact@v3
      with:
        name: rpm-build-result
        path: RPMS/

