name: Build Storeman

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir RPMS

    - name: Build 3.3.0.14-armv7hl
      env:
        RELEASE: 3.3.0.14
        ARCH: armv7hl
      run: bash ./scripts/gha-build.sh

    - name: Build 3.3.0.14-i486
      env:
        RELEASE: 3.3.0.14
        ARCH: i486
      run: bash ./scripts/gha-build.sh

    - name: Build 3.4.0.24-armv7hl
      env:
        RELEASE: 3.4.0.24
        LATEST_RELEASE: 1
        ARCH: armv7hl
      run: bash ./scripts/gha-build.sh

    - name: Build 3.4.0.24-i486
      env:
        RELEASE: 3.4.0.24
        LATEST_RELEASE: 1
        ARCH: i486
      run: bash ./scripts/gha-build.sh

    - name: Create release
      run: bash ./scripts/gha-release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
