name: CI - sfos3.3 branch on SFOS 3.3.0 (armv7hl,i486) & SFOS 4.0.1 (aarch64)

env:
  RELEASE: 3.3.0.14

on:
  push:
    tags:
      - 'release*_sfos3.3/*'
      - 'rc*_sfos3.3/*'
      - 'beta*_sfos3.3/*'
      - 'alpha*_sfos3.3/*'
      - 'sfos3.3/*'
  pull_request:
    branches:
      - sfos3.3

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Caching Docker images is not ready yet, see 
    # https://github.com/storeman-developers/harbour-storeman-installer/blob/devel/cache-docker-images_github-ci.md
    #- name: Cache Docker images of the Sailfish-SDK
    #  id: cache-sdk
    #  uses: actions/cache@v3
    #  with:
    #    path: $GITHUB_WORKSPACE/â€¦
    #    key: cache

    - name: Prepare
      run: mkdir RPMS

    - name: Build aarch64 on 4.0.1.45
      uses: coderus/github-sfos-build@old-stable
      with:
        release: 4.0.1.45
        arch: aarch64

    - name: Build armv7hl on ${{ env.RELEASE }}
      uses: coderus/github-sfos-build@old-stable
      with:
        release: ${{ env.RELEASE }}
        arch: armv7hl

    - name: Build i486 on ${{ env.RELEASE }}
      uses: coderus/github-sfos-build@old-stable
      with:
        release: ${{ env.RELEASE }}
        arch: i486

    - name: Upload build results
      uses: actions/upload-artifact@v3
      with:
        name: RPM-build-results_sfos3.3.0-4.1.0
        path: RPMS/
